export const SMC_CONSTANTS = {
  API_TOKEN: "SMC_API_TOKEN",
  ROLE: {
    ADMIN: "ADMIN",
    USER: "USER"
  },
  IMPORT_RESULT_REPORT: "IMPORT_RESULT_REPORT"
};

export const SMC_EVENTS = {
  USER_LOADED: "USER_LOADED"
}

