-- MySQL Script generated by MySQL Workbench
-- Wed May 13 18:44:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smcdb
-- -----------------------------------------------------
-- Stock marketing charting exercise database

-- -----------------------------------------------------
-- Schema smcdb
--
-- Stock marketing charting exercise database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smcdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `smcdb` ;

-- -----------------------------------------------------
-- Table `smcdb`.`tb_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_company` (
  `id` VARCHAR(36) NOT NULL DEFAULT 'uuid()',
  `name` VARCHAR(128) NULL,
  `turn_over` DECIMAL(16,2) NULL,
  `ceo` VARCHAR(128) NULL,
  `board_of_directors` VARCHAR(256) NULL,
  `brief_write_up` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smcdb`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_user` (
  `username` VARCHAR(32) CHARACTER SET 'DEFAULT' NOT NULL,
  `email` VARCHAR(32) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `mobile` VARCHAR(16) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_upd_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_type` VARCHAR(8) NOT NULL DEFAULT 'USER' COMMENT 'ADMIN/USER',
  PRIMARY KEY (`email`));


-- -----------------------------------------------------
-- Table `smcdb`.`tb_stock_exchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_stock_exchange` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(64) NULL,
  `short_name` VARCHAR(8) NULL,
  `region` VARCHAR(64) NULL,
  `brief` VARCHAR(512) NULL,
  `contact_address` VARCHAR(128) NULL,
  `remarks` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `short_name_UNIQUE` (`short_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smcdb`.`tb_company_exchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_company_exchange` (
  `id` VARCHAR(36) NOT NULL,
  `comp_id` VARCHAR(36) NULL,
  `exchange_id` VARCHAR(36) NULL,
  `stock_code` VARCHAR(8) NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_EXCHANGE_ID_idx` (`exchange_id` ASC),
  UNIQUE INDEX `UNIQUE_CODE` (`comp_id` ASC, `exchange_id` ASC, `stock_code` ASC),
  CONSTRAINT `FK_COMP_ID0`
    FOREIGN KEY (`comp_id`)
    REFERENCES `smcdb`.`tb_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_EXCHANGE_ID0`
    FOREIGN KEY (`exchange_id`)
    REFERENCES `smcdb`.`tb_stock_exchange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smcdb`.`tb_ipo_planned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_ipo_planned` (
  `id` VARCHAR(36) NOT NULL,
  `price_per_share` DECIMAL(8,2) NULL,
  `total_share` DECIMAL(16,0) NULL,
  `open_date` DATE NULL,
  `remarks` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_ID`
    FOREIGN KEY (`id`)
    REFERENCES `smcdb`.`tb_company_exchange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smcdb`.`tb_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_sector` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(64) NULL,
  `brief` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smcdb`.`tb_company_has_tb_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_company_has_tb_company` (
  `tb_company_id` VARCHAR(48) NOT NULL,
  `tb_company_id1` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`tb_company_id`, `tb_company_id1`),
  INDEX `fk_tb_company_has_tb_company_tb_company2_idx` (`tb_company_id1` ASC),
  INDEX `fk_tb_company_has_tb_company_tb_company1_idx` (`tb_company_id` ASC),
  CONSTRAINT `fk_tb_company_has_tb_company_tb_company1`
    FOREIGN KEY (`tb_company_id`)
    REFERENCES `smcdb`.`tb_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_company_has_tb_company_tb_company2`
    FOREIGN KEY (`tb_company_id1`)
    REFERENCES `smcdb`.`tb_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smcdb`.`tb_company_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_company_sector` (
  `tb_company_id` VARCHAR(36) NOT NULL,
  `tb_sector_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`tb_company_id`, `tb_sector_id`),
  INDEX `fk_tb_sector1_idx` (`tb_sector_id` ASC),
  INDEX `fk_tb_company1_idx` (`tb_company_id` ASC),
  CONSTRAINT `fk_tb_company1`
    FOREIGN KEY (`tb_company_id`)
    REFERENCES `smcdb`.`tb_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_sector1`
    FOREIGN KEY (`tb_sector_id`)
    REFERENCES `smcdb`.`tb_sector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smcdb`.`tb_company_stock_exchange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_company_stock_exchange` (
  `tb_company_id` VARCHAR(48) NOT NULL,
  `tb_stock_exchange_id` VARCHAR(48) NOT NULL,
  `stock_code` VARCHAR(45) NULL,
  PRIMARY KEY (`tb_company_id`, `tb_stock_exchange_id`),
  INDEX `fk_tb_stock_exchange1_idx` (`tb_stock_exchange_id` ASC),
  INDEX `fk_tb_company1_idx` (`tb_company_id` ASC),
  CONSTRAINT `fk_tb_company1`
    FOREIGN KEY (`tb_company_id`)
    REFERENCES `smcdb`.`tb_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_stock_exchange1`
    FOREIGN KEY (`tb_stock_exchange_id`)
    REFERENCES `smcdb`.`tb_stock_exchange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smcdb`.`tb_stock_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`tb_stock_price` (
  `id` VARCHAR(36) NULL,
  `price` DECIMAL(8,2) NULL,
  `date` DATE NULL,
  `remarks` VARCHAR(256) NULL,
  UNIQUE INDEX `UNIQ_CE_DATE` (`date` ASC, `id` ASC),
  INDEX `FK_CE_ID_idx` (`id` ASC),
  CONSTRAINT `FK_CE_ID`
    FOREIGN KEY (`id`)
    REFERENCES `smcdb`.`tb_company_exchange` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `smcdb` ;

-- -----------------------------------------------------
-- Placeholder table for view `smcdb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `smcdb`.`vw_stock_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smcdb`.`vw_stock_price` (`id` INT, `date` INT, `price` INT, `comp_id` INT, `exchange_id` INT, `stock_code` INT);

-- -----------------------------------------------------
-- View `smcdb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smcdb`.`view1`;
USE `smcdb`;


-- -----------------------------------------------------
-- View `smcdb`.`vw_stock_price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smcdb`.`vw_stock_price`;
USE `smcdb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`%` 
    SQL SECURITY DEFINER
VIEW `smcdb`.`vw_stock_price` AS
    SELECT 
        `sp`.`id` AS `id`,
        `sp`.`date` AS `date`,
        `sp`.`price` AS `price`,
        `ce`.`comp_id` AS `comp_id`,
        `ce`.`exchange_id` AS `exchange_id`,
        `ce`.`stock_code` AS `stock_code`
    FROM
        ((`smcdb`.`tb_stock_price` `sp`
        LEFT JOIN `smcdb`.`tb_company_exchange` `ce` ON ((`sp`.`company_exchange_id` = `ce`.`id`)))
        JOIN `smcdb`.`tb_company` `c` ON ((`c`.`id` = `ce`.`comp_id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
